// <auto-generated />
using System;
using AdminFlow.Budget.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminFlow.Budget.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260817191521_AddExpenseRequests")]
    partial class AddExpenseRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminFlow.Budget.Domain.Budgets.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Allocated")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("allocated");

                    b.Property<decimal>("Committed")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("committed");

                    b.Property<Guid>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("CostCenterId", "FiscalYear")
                        .IsUnique()
                        .HasDatabaseName("ux_budgets_cost_center_fiscal_year");

                    b.ToTable("budgets", null, t =>
                        {
                            t.HasCheckConstraint("ck_budgets_allocated_positive", "allocated > 0");

                            t.HasCheckConstraint("ck_budgets_committed_non_negative", "committed >= 0");

                            t.HasCheckConstraint("ck_budgets_committed_within_allocation", "committed <= allocated");

                            t.HasCheckConstraint("ck_budgets_fiscal_year", "fiscal_year BETWEEN 1 AND 9999");
                        });
                });

            modelBuilder.Entity("AdminFlow.Budget.Domain.CostCenters.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cost_centers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_cost_centers_code");

                    b.ToTable("cost_centers", (string)null);
                });

            modelBuilder.Entity("AdminFlow.Budget.Domain.ExpenseRequests.ExpenseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_expense_requests");

                    b.HasIndex("BudgetId")
                        .HasDatabaseName("ix_expense_requests_budget_id");

                    b.ToTable("expense_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_expense_requests_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_expense_requests_status_valid", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("AdminFlow.Budget.Domain.Budgets.Budget", b =>
                {
                    b.HasOne("AdminFlow.Budget.Domain.CostCenters.CostCenter", null)
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_cost_centers");
                });

            modelBuilder.Entity("AdminFlow.Budget.Domain.ExpenseRequests.ExpenseRequest", b =>
                {
                    b.HasOne("AdminFlow.Budget.Domain.Budgets.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_requests_budgets");
                });
#pragma warning restore 612, 618
        }
    }
}
